#! /usr/bin/python3

import sys
import argparse

'''Extracts reads from fastq file generated by MINKNOW'''
def multi_fasta(fastq, cut_off, output):
    i = 0
    fd=open(output,"w")
    with open(fastq, "r") as f:
        f = [lines.strip() for lines in f]
        reads = f[1::4]
        for x, read in enumerate(reads):

            if len(read) > cut_off:
                i += 1
                fd.write("\n>_read_number{}\n".format(x) + read)
            else:
                pass
    print("Reads saved:", i)
    fd.close()


def main(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("DNAfastq", help="Enter DNA-seq fastq file")
    parser.add_argument("cut_off", type=int, help="Enter cut-off length")
    parser.add_argument("output", help="Enter output filename")
    args = parser.parse_args()
    try:

        if args:
            multi_fasta(args.DNAfastq, args.cut_off, args.output)
        else:
            raise AttributeError

    except AttributeError as a:
        parser.print_help()


if __name__ == '__main__':
    main(sys.argv)
